#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="carrito_compras")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcarrito(carrito instance);
    partial void Updatecarrito(carrito instance);
    partial void Deletecarrito(carrito instance);
    partial void Insertproducto(producto instance);
    partial void Updateproducto(producto instance);
    partial void Deleteproducto(producto instance);
    partial void Insertusuario_registro(usuario_registro instance);
    partial void Updateusuario_registro(usuario_registro instance);
    partial void Deleteusuario_registro(usuario_registro instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.carrito_comprasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<carrito> carrito
		{
			get
			{
				return this.GetTable<carrito>();
			}
		}
		
		public System.Data.Linq.Table<producto> producto
		{
			get
			{
				return this.GetTable<producto>();
			}
		}
		
		public System.Data.Linq.Table<usuario_registro> usuario_registro
		{
			get
			{
				return this.GetTable<usuario_registro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrito")]
	public partial class carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_carrito;
		
		private System.Nullable<int> _id_usu;
		
		private System.Nullable<int> _id_pro;
		
		private System.Nullable<int> _cantidad;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<usuario_registro> _usuario_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carritoChanging(int value);
    partial void Onid_carritoChanged();
    partial void Onid_usuChanging(System.Nullable<int> value);
    partial void Onid_usuChanged();
    partial void Onid_proChanging(System.Nullable<int> value);
    partial void Onid_proChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public carrito()
		{
			this._producto = default(EntityRef<producto>);
			this._usuario_registro = default(EntityRef<usuario_registro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrito", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_carrito
		{
			get
			{
				return this._id_carrito;
			}
			set
			{
				if ((this._id_carrito != value))
				{
					this.Onid_carritoChanging(value);
					this.SendPropertyChanging();
					this._id_carrito = value;
					this.SendPropertyChanged("id_carrito");
					this.Onid_carritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", DbType="Int")]
		public System.Nullable<int> id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					if (this._usuario_registro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuChanging(value);
					this.SendPropertyChanging();
					this._id_usu = value;
					this.SendPropertyChanged("id_usu");
					this.Onid_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", DbType="Int")]
		public System.Nullable<int> id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_producto", ThisKey="id_pro", OtherKey="id_pro", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_pro = value.id_pro;
					}
					else
					{
						this._id_pro = default(Nullable<int>);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_registro_carrito", Storage="_usuario_registro", ThisKey="id_usu", OtherKey="id_usu", IsForeignKey=true)]
		public usuario_registro usuario_registro
		{
			get
			{
				return this._usuario_registro.Entity;
			}
			set
			{
				usuario_registro previousValue = this._usuario_registro.Entity;
				if (((previousValue != value) 
							|| (this._usuario_registro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario_registro.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._usuario_registro.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_usu = value.id_usu;
					}
					else
					{
						this._id_usu = default(Nullable<int>);
					}
					this.SendPropertyChanged("usuario_registro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pro;
		
		private string _nombre_pro;
		
		private string _descrip_pro;
		
		private System.Nullable<decimal> _precio_pro;
		
		private EntitySet<carrito> _carrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proChanging(int value);
    partial void Onid_proChanged();
    partial void Onnombre_proChanging(string value);
    partial void Onnombre_proChanged();
    partial void Ondescrip_proChanging(string value);
    partial void Ondescrip_proChanged();
    partial void Onprecio_proChanging(System.Nullable<decimal> value);
    partial void Onprecio_proChanged();
    #endregion
		
		public producto()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_pro", DbType="VarChar(100)")]
		public string nombre_pro
		{
			get
			{
				return this._nombre_pro;
			}
			set
			{
				if ((this._nombre_pro != value))
				{
					this.Onnombre_proChanging(value);
					this.SendPropertyChanging();
					this._nombre_pro = value;
					this.SendPropertyChanged("nombre_pro");
					this.Onnombre_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrip_pro", DbType="VarChar(500)")]
		public string descrip_pro
		{
			get
			{
				return this._descrip_pro;
			}
			set
			{
				if ((this._descrip_pro != value))
				{
					this.Ondescrip_proChanging(value);
					this.SendPropertyChanging();
					this._descrip_pro = value;
					this.SendPropertyChanged("descrip_pro");
					this.Ondescrip_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_pro", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_pro
		{
			get
			{
				return this._precio_pro;
			}
			set
			{
				if ((this._precio_pro != value))
				{
					this.Onprecio_proChanging(value);
					this.SendPropertyChanging();
					this._precio_pro = value;
					this.SendPropertyChanged("precio_pro");
					this.Onprecio_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_carrito", ThisKey="id_pro", OtherKey="id_pro")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario_registro")]
	public partial class usuario_registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usu;
		
		private string _nombre_usu;
		
		private string _correo_usu;
		
		private string _pass_usu;
		
		private string _domicilio_usu;
		
		private System.Nullable<int> _num_usu;
		
		private EntitySet<carrito> _carrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuChanging(int value);
    partial void Onid_usuChanged();
    partial void Onnombre_usuChanging(string value);
    partial void Onnombre_usuChanged();
    partial void Oncorreo_usuChanging(string value);
    partial void Oncorreo_usuChanged();
    partial void Onpass_usuChanging(string value);
    partial void Onpass_usuChanged();
    partial void Ondomicilio_usuChanging(string value);
    partial void Ondomicilio_usuChanged();
    partial void Onnum_usuChanging(System.Nullable<int> value);
    partial void Onnum_usuChanged();
    #endregion
		
		public usuario_registro()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					this.Onid_usuChanging(value);
					this.SendPropertyChanging();
					this._id_usu = value;
					this.SendPropertyChanged("id_usu");
					this.Onid_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usu", DbType="VarChar(100)")]
		public string nombre_usu
		{
			get
			{
				return this._nombre_usu;
			}
			set
			{
				if ((this._nombre_usu != value))
				{
					this.Onnombre_usuChanging(value);
					this.SendPropertyChanging();
					this._nombre_usu = value;
					this.SendPropertyChanged("nombre_usu");
					this.Onnombre_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_usu", DbType="VarChar(100)")]
		public string correo_usu
		{
			get
			{
				return this._correo_usu;
			}
			set
			{
				if ((this._correo_usu != value))
				{
					this.Oncorreo_usuChanging(value);
					this.SendPropertyChanging();
					this._correo_usu = value;
					this.SendPropertyChanged("correo_usu");
					this.Oncorreo_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usu", DbType="VarChar(100)")]
		public string pass_usu
		{
			get
			{
				return this._pass_usu;
			}
			set
			{
				if ((this._pass_usu != value))
				{
					this.Onpass_usuChanging(value);
					this.SendPropertyChanging();
					this._pass_usu = value;
					this.SendPropertyChanged("pass_usu");
					this.Onpass_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domicilio_usu", DbType="VarChar(200)")]
		public string domicilio_usu
		{
			get
			{
				return this._domicilio_usu;
			}
			set
			{
				if ((this._domicilio_usu != value))
				{
					this.Ondomicilio_usuChanging(value);
					this.SendPropertyChanging();
					this._domicilio_usu = value;
					this.SendPropertyChanged("domicilio_usu");
					this.Ondomicilio_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_usu", DbType="Int")]
		public System.Nullable<int> num_usu
		{
			get
			{
				return this._num_usu;
			}
			set
			{
				if ((this._num_usu != value))
				{
					this.Onnum_usuChanging(value);
					this.SendPropertyChanging();
					this._num_usu = value;
					this.SendPropertyChanged("num_usu");
					this.Onnum_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_registro_carrito", Storage="_carrito", ThisKey="id_usu", OtherKey="id_usu")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario_registro = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario_registro = null;
		}
	}
}
#pragma warning restore 1591
