#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="carrito_compras")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcarrito(carrito instance);
    partial void Updatecarrito(carrito instance);
    partial void Deletecarrito(carrito instance);
    partial void Insertproducto(producto instance);
    partial void Updateproducto(producto instance);
    partial void Deleteproducto(producto instance);
    partial void Inserttbl_categoria(tbl_categoria instance);
    partial void Updatetbl_categoria(tbl_categoria instance);
    partial void Deletetbl_categoria(tbl_categoria instance);
    partial void Inserttbl_metpago(tbl_metpago instance);
    partial void Updatetbl_metpago(tbl_metpago instance);
    partial void Deletetbl_metpago(tbl_metpago instance);
    partial void Inserttbl_proveedores(tbl_proveedores instance);
    partial void Updatetbl_proveedores(tbl_proveedores instance);
    partial void Deletetbl_proveedores(tbl_proveedores instance);
    partial void Insertusuario_registro(usuario_registro instance);
    partial void Updateusuario_registro(usuario_registro instance);
    partial void Deleteusuario_registro(usuario_registro instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.carrito_comprasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<carrito> carrito
		{
			get
			{
				return this.GetTable<carrito>();
			}
		}
		
		public System.Data.Linq.Table<producto> producto
		{
			get
			{
				return this.GetTable<producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_categoria> tbl_categoria
		{
			get
			{
				return this.GetTable<tbl_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tbl_metpago> tbl_metpago
		{
			get
			{
				return this.GetTable<tbl_metpago>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedores> tbl_proveedores
		{
			get
			{
				return this.GetTable<tbl_proveedores>();
			}
		}
		
		public System.Data.Linq.Table<usuario_registro> usuario_registro
		{
			get
			{
				return this.GetTable<usuario_registro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrito")]
	public partial class carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_carrito;
		
		private System.Nullable<int> _id_usu;
		
		private System.Nullable<int> _id_pro;
		
		private System.Nullable<int> _cantidad;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<usuario_registro> _usuario_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carritoChanging(int value);
    partial void Onid_carritoChanged();
    partial void Onid_usuChanging(System.Nullable<int> value);
    partial void Onid_usuChanged();
    partial void Onid_proChanging(System.Nullable<int> value);
    partial void Onid_proChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public carrito()
		{
			this._producto = default(EntityRef<producto>);
			this._usuario_registro = default(EntityRef<usuario_registro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrito", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_carrito
		{
			get
			{
				return this._id_carrito;
			}
			set
			{
				if ((this._id_carrito != value))
				{
					this.Onid_carritoChanging(value);
					this.SendPropertyChanging();
					this._id_carrito = value;
					this.SendPropertyChanged("id_carrito");
					this.Onid_carritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", DbType="Int")]
		public System.Nullable<int> id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					if (this._usuario_registro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuChanging(value);
					this.SendPropertyChanging();
					this._id_usu = value;
					this.SendPropertyChanged("id_usu");
					this.Onid_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", DbType="Int")]
		public System.Nullable<int> id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_producto", ThisKey="id_pro", OtherKey="id_pro", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_pro = value.id_pro;
					}
					else
					{
						this._id_pro = default(Nullable<int>);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_registro_carrito", Storage="_usuario_registro", ThisKey="id_usu", OtherKey="id_usu", IsForeignKey=true)]
		public usuario_registro usuario_registro
		{
			get
			{
				return this._usuario_registro.Entity;
			}
			set
			{
				usuario_registro previousValue = this._usuario_registro.Entity;
				if (((previousValue != value) 
							|| (this._usuario_registro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario_registro.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._usuario_registro.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_usu = value.id_usu;
					}
					else
					{
						this._id_usu = default(Nullable<int>);
					}
					this.SendPropertyChanged("usuario_registro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pro;
		
		private string _nombre_pro;
		
		private string _descrip_pro;
		
		private System.Nullable<decimal> _precio_pro;
		
		private System.Nullable<int> _id_proveedor;
		
		private System.Nullable<int> _id_categoria;
		
		private System.Nullable<int> _id_metpago;
		
		private EntitySet<carrito> _carrito;
		
		private EntityRef<tbl_categoria> _tbl_categoria;
		
		private EntityRef<tbl_metpago> _tbl_metpago;
		
		private EntityRef<tbl_proveedores> _tbl_proveedores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proChanging(int value);
    partial void Onid_proChanged();
    partial void Onnombre_proChanging(string value);
    partial void Onnombre_proChanged();
    partial void Ondescrip_proChanging(string value);
    partial void Ondescrip_proChanged();
    partial void Onprecio_proChanging(System.Nullable<decimal> value);
    partial void Onprecio_proChanged();
    partial void Onid_proveedorChanging(System.Nullable<int> value);
    partial void Onid_proveedorChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    partial void Onid_metpagoChanging(System.Nullable<int> value);
    partial void Onid_metpagoChanged();
    #endregion
		
		public producto()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			this._tbl_categoria = default(EntityRef<tbl_categoria>);
			this._tbl_metpago = default(EntityRef<tbl_metpago>);
			this._tbl_proveedores = default(EntityRef<tbl_proveedores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_pro", DbType="VarChar(100)")]
		public string nombre_pro
		{
			get
			{
				return this._nombre_pro;
			}
			set
			{
				if ((this._nombre_pro != value))
				{
					this.Onnombre_proChanging(value);
					this.SendPropertyChanging();
					this._nombre_pro = value;
					this.SendPropertyChanged("nombre_pro");
					this.Onnombre_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrip_pro", DbType="VarChar(500)")]
		public string descrip_pro
		{
			get
			{
				return this._descrip_pro;
			}
			set
			{
				if ((this._descrip_pro != value))
				{
					this.Ondescrip_proChanging(value);
					this.SendPropertyChanging();
					this._descrip_pro = value;
					this.SendPropertyChanged("descrip_pro");
					this.Ondescrip_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_pro", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_pro
		{
			get
			{
				return this._precio_pro;
			}
			set
			{
				if ((this._precio_pro != value))
				{
					this.Onprecio_proChanging(value);
					this.SendPropertyChanging();
					this._precio_pro = value;
					this.SendPropertyChanged("precio_pro");
					this.Onprecio_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int")]
		public System.Nullable<int> id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					if (this._tbl_proveedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tbl_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_metpago", DbType="Int")]
		public System.Nullable<int> id_metpago
		{
			get
			{
				return this._id_metpago;
			}
			set
			{
				if ((this._id_metpago != value))
				{
					if (this._tbl_metpago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_metpagoChanging(value);
					this.SendPropertyChanging();
					this._id_metpago = value;
					this.SendPropertyChanged("id_metpago");
					this.Onid_metpagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_carrito", ThisKey="id_pro", OtherKey="id_pro")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_producto", Storage="_tbl_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tbl_categoria tbl_categoria
		{
			get
			{
				return this._tbl_categoria.Entity;
			}
			set
			{
				tbl_categoria previousValue = this._tbl_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tbl_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_categoria.Entity = null;
						previousValue.producto.Remove(this);
					}
					this._tbl_categoria.Entity = value;
					if ((value != null))
					{
						value.producto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_metpago_producto", Storage="_tbl_metpago", ThisKey="id_metpago", OtherKey="id_metpago", IsForeignKey=true)]
		public tbl_metpago tbl_metpago
		{
			get
			{
				return this._tbl_metpago.Entity;
			}
			set
			{
				tbl_metpago previousValue = this._tbl_metpago.Entity;
				if (((previousValue != value) 
							|| (this._tbl_metpago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_metpago.Entity = null;
						previousValue.producto.Remove(this);
					}
					this._tbl_metpago.Entity = value;
					if ((value != null))
					{
						value.producto.Add(this);
						this._id_metpago = value.id_metpago;
					}
					else
					{
						this._id_metpago = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_metpago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedores_producto", Storage="_tbl_proveedores", ThisKey="id_proveedor", OtherKey="id_proveedor", IsForeignKey=true)]
		public tbl_proveedores tbl_proveedores
		{
			get
			{
				return this._tbl_proveedores.Entity;
			}
			set
			{
				tbl_proveedores previousValue = this._tbl_proveedores.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedores.Entity = null;
						previousValue.producto.Remove(this);
					}
					this._tbl_proveedores.Entity = value;
					if ((value != null))
					{
						value.producto.Add(this);
						this._id_proveedor = value.id_proveedor;
					}
					else
					{
						this._id_proveedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_categoria")]
	public partial class tbl_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _categoria;
		
		private EntitySet<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    #endregion
		
		public tbl_categoria()
		{
			this._producto = new EntitySet<producto>(new Action<producto>(this.attach_producto), new Action<producto>(this.detach_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(100)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_producto", Storage="_producto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<producto> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = this;
		}
		
		private void detach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_metpago")]
	public partial class tbl_metpago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_metpago;
		
		private string _metodo;
		
		private EntitySet<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_metpagoChanging(int value);
    partial void Onid_metpagoChanged();
    partial void OnmetodoChanging(string value);
    partial void OnmetodoChanged();
    #endregion
		
		public tbl_metpago()
		{
			this._producto = new EntitySet<producto>(new Action<producto>(this.attach_producto), new Action<producto>(this.detach_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_metpago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_metpago
		{
			get
			{
				return this._id_metpago;
			}
			set
			{
				if ((this._id_metpago != value))
				{
					this.Onid_metpagoChanging(value);
					this.SendPropertyChanging();
					this._id_metpago = value;
					this.SendPropertyChanged("id_metpago");
					this.Onid_metpagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo", DbType="VarChar(100)")]
		public string metodo
		{
			get
			{
				return this._metodo;
			}
			set
			{
				if ((this._metodo != value))
				{
					this.OnmetodoChanging(value);
					this.SendPropertyChanging();
					this._metodo = value;
					this.SendPropertyChanged("metodo");
					this.OnmetodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_metpago_producto", Storage="_producto", ThisKey="id_metpago", OtherKey="id_metpago")]
		public EntitySet<producto> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_metpago = this;
		}
		
		private void detach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_metpago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedores")]
	public partial class tbl_proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_proveedor;
		
		private string _nombre_proveedor;
		
		private string _direccion_proveedor;
		
		private string _telefono_proveedor;
		
		private EntitySet<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proveedorChanging(int value);
    partial void Onid_proveedorChanged();
    partial void Onnombre_proveedorChanging(string value);
    partial void Onnombre_proveedorChanged();
    partial void Ondireccion_proveedorChanging(string value);
    partial void Ondireccion_proveedorChanged();
    partial void Ontelefono_proveedorChanging(string value);
    partial void Ontelefono_proveedorChanged();
    #endregion
		
		public tbl_proveedores()
		{
			this._producto = new EntitySet<producto>(new Action<producto>(this.attach_producto), new Action<producto>(this.detach_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_proveedor", DbType="VarChar(100)")]
		public string nombre_proveedor
		{
			get
			{
				return this._nombre_proveedor;
			}
			set
			{
				if ((this._nombre_proveedor != value))
				{
					this.Onnombre_proveedorChanging(value);
					this.SendPropertyChanging();
					this._nombre_proveedor = value;
					this.SendPropertyChanged("nombre_proveedor");
					this.Onnombre_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_proveedor", DbType="VarChar(100)")]
		public string direccion_proveedor
		{
			get
			{
				return this._direccion_proveedor;
			}
			set
			{
				if ((this._direccion_proveedor != value))
				{
					this.Ondireccion_proveedorChanging(value);
					this.SendPropertyChanging();
					this._direccion_proveedor = value;
					this.SendPropertyChanged("direccion_proveedor");
					this.Ondireccion_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_proveedor", DbType="VarChar(100)")]
		public string telefono_proveedor
		{
			get
			{
				return this._telefono_proveedor;
			}
			set
			{
				if ((this._telefono_proveedor != value))
				{
					this.Ontelefono_proveedorChanging(value);
					this.SendPropertyChanging();
					this._telefono_proveedor = value;
					this.SendPropertyChanged("telefono_proveedor");
					this.Ontelefono_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedores_producto", Storage="_producto", ThisKey="id_proveedor", OtherKey="id_proveedor")]
		public EntitySet<producto> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedores = this;
		}
		
		private void detach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario_registro")]
	public partial class usuario_registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usu;
		
		private string _nombre_usu;
		
		private string _correo_usu;
		
		private string _pass_usu;
		
		private string _domicilio_usu;
		
		private System.Nullable<int> _num_usu;
		
		private EntitySet<carrito> _carrito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuChanging(int value);
    partial void Onid_usuChanged();
    partial void Onnombre_usuChanging(string value);
    partial void Onnombre_usuChanged();
    partial void Oncorreo_usuChanging(string value);
    partial void Oncorreo_usuChanged();
    partial void Onpass_usuChanging(string value);
    partial void Onpass_usuChanged();
    partial void Ondomicilio_usuChanging(string value);
    partial void Ondomicilio_usuChanged();
    partial void Onnum_usuChanging(System.Nullable<int> value);
    partial void Onnum_usuChanged();
    #endregion
		
		public usuario_registro()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usu
		{
			get
			{
				return this._id_usu;
			}
			set
			{
				if ((this._id_usu != value))
				{
					this.Onid_usuChanging(value);
					this.SendPropertyChanging();
					this._id_usu = value;
					this.SendPropertyChanged("id_usu");
					this.Onid_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usu", DbType="VarChar(100)")]
		public string nombre_usu
		{
			get
			{
				return this._nombre_usu;
			}
			set
			{
				if ((this._nombre_usu != value))
				{
					this.Onnombre_usuChanging(value);
					this.SendPropertyChanging();
					this._nombre_usu = value;
					this.SendPropertyChanged("nombre_usu");
					this.Onnombre_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_usu", DbType="VarChar(100)")]
		public string correo_usu
		{
			get
			{
				return this._correo_usu;
			}
			set
			{
				if ((this._correo_usu != value))
				{
					this.Oncorreo_usuChanging(value);
					this.SendPropertyChanging();
					this._correo_usu = value;
					this.SendPropertyChanged("correo_usu");
					this.Oncorreo_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usu", DbType="VarChar(100)")]
		public string pass_usu
		{
			get
			{
				return this._pass_usu;
			}
			set
			{
				if ((this._pass_usu != value))
				{
					this.Onpass_usuChanging(value);
					this.SendPropertyChanging();
					this._pass_usu = value;
					this.SendPropertyChanged("pass_usu");
					this.Onpass_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domicilio_usu", DbType="VarChar(200)")]
		public string domicilio_usu
		{
			get
			{
				return this._domicilio_usu;
			}
			set
			{
				if ((this._domicilio_usu != value))
				{
					this.Ondomicilio_usuChanging(value);
					this.SendPropertyChanging();
					this._domicilio_usu = value;
					this.SendPropertyChanged("domicilio_usu");
					this.Ondomicilio_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_usu", DbType="Int")]
		public System.Nullable<int> num_usu
		{
			get
			{
				return this._num_usu;
			}
			set
			{
				if ((this._num_usu != value))
				{
					this.Onnum_usuChanging(value);
					this.SendPropertyChanging();
					this._num_usu = value;
					this.SendPropertyChanged("num_usu");
					this.Onnum_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_registro_carrito", Storage="_carrito", ThisKey="id_usu", OtherKey="id_usu")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario_registro = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario_registro = null;
		}
	}
}
#pragma warning restore 1591
